### ISSUE TITLE
White page when open ticket

### ISSUE THREAD

**Issue by Jahsis** [kayako/whmcs-integration#28]
I can submit new ticket, can list tickets, but when I open ticket, shows only white blank page. Where should I look for problem?

**Comment by DrundoSoft** [comment]
We have the same issue with 6.1.1 version and this integration is useless if we can't see list of tickets.

**Comment by christoph12** [comment]
How can this be fixed? We are evaluating Kayako but with this bug, it's a no go.

**Comment by gurpreetburmi31** [comment]
Hi @christoph12!

Have you created a support Ticket ? We have a fix for this defect.

Regards,

Gurpreet Singh

**Comment by mansiwason** [comment]
We have fixed this issue with the current master build.
Commit is - https://github.com/kayako/whmcs-integration/commit/6a3b6453be4d2836008de8ed541fb7003c1a9bd2

Please find the same.
