### ISSUE TITLE
Blank page on submit ticket page using WHMCS 7.1.1

### ISSUE THREAD

**Issue by akashsethi1989** [kayako/whmcs-integration#50]
We need to make the integration compatible with WHMCS 7.1.1

**Comment by sarwanjassi** [comment]
Thanks Akash. Keep us updated when you fix your API.

**Comment by mansiwason** [comment]
The Kayako module is compatible with the WHMCS 7.1 version. Please get the module from https://github.com/kayako/whmcs-integration 

Feel free to revert in case of any assistance needed.
